### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by AlexKurek** [ericmandel/pyds9#106] opened 2022-08-14 13:41 UTC
http://ds9.si.edu/ref/xpa.html
http://hea-www.harvard.edu/saord/xpa
from here:
https://het.as.utexas.edu/HET/Software/pyDS9/
are both not working.

Best regards,
Alexander Kurek

**Comment by ericmandel** [comment] 2022-08-14 17:13
pyds9 is no longer supported, at least by me ... I am no longer involved in
astrophysics software. But I still own the repository, so if you want to
look into the cause of this problem using the github sources and make a PR,
I will almost certainly merge it.

**Comment by AlexKurek** [comment] 2022-08-15 06:17
I dont have an access to https://het.as.utexas.edu/HET/Software/pyDS9/ and I dont know if there are any new WWW that replaced
http://ds9.si.edu/ref/xpa.html
and
http://hea-www.harvard.edu/saord/xpa
So I dont think Im able to do this

**Comment by ericmandel** [comment] 2022-08-15 11:43
I don't have access to the utexas.edu URL either. The xpa reference page on
the ds9 web site is now https://ds9.si.edu/doc/ref/xpa.html and the xpa
source is on github at https://github.com/ericmandel/xpa.

What I meant  about a PR was that if the Python help page is generated
somehow from the github source and If you know how to do this (I do not
know), you could change the two URLs and remake the help page, submit a PR,
and let the utexas.edu web admin know that the links in the help page have
been updated. Not sure if this is worth your time ...

**Comment by AlexKurek** [comment] 2022-08-15 12:29
I downloaded both https://github.com/ericmandel/pyds9 and https://github.com/ericmandel/xpa and searched for the phrase "http://ds9.si.edu/ref/xpa.html". Its not there. So I think we cannot do this via github.

**Comment by ericmandel** [comment] 2022-08-15 13:15
Yes, I also looked briefly and did not see anything. So I don't know how that utexas.edu document was created. I'm going to close this issue.

**Closed as completed by ericmandel** 2022-08-15 13:15 UTC
